version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/clojure:tools-deps # ...with this image as the primary container; this is where all `steps` will run
    environment: # environment variables for primary container
      JVM_OPTS: -Xmx3200m # limit the maximum heap size to prevent out of memory errors
    steps: # commands that comprise the `build` job
      - checkout # check out source code to working directory
      - restore_cache: # restores saved cache if checksum hasn't changed since the last run
          key: teet-clojure-{{ checksum "deps.edn" }}
      - run: cd app/frontend && clojure -A:test
      - save_cache: # generate and store cache in the .m2 directory using a key template
          paths:
            - ~/.m2
          key: teet-clojure-{{ checksum "deps.edn" }}
