version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Download Clojure CLI tool
      - curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
      - bash linux-install-1.10.1.466.sh
  build:
    commands:
      - (cd ci/deploy; bash deploy_json.bash deploying)
      - cd db && bash migrate.bash && cd ..
      - cd ci/deploy
      - bash api.bash
      - bash frontend.bash
      - bash datomic.bash
      - bash deploy_json.bash deployed


  post_build:
    commands:
      - NOTIFY_ON_SUCCESS=1 bash $CODEBUILD_SRC_DIR/ci/scripts/slack.bash Deploy $COMMIT
cache:
  paths:
    - '/root/.m2/**/*'
