version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    COMMIT: ""

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Download Clojure CLI tool
      - curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
      - bash linux-install-1.10.1.466.sh
  build:
    commands:
      - cd ci/deploy
      - bash frontend.bash
      - bash datomic.bash
